server:
  port: 8185
  servlet:
    context-path: /event-query-web-client

event-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://localhost:8184/event-query-service/documents'
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${event-query-web-client.webclient.accept-type}
  query-by-task:
    method: POST
    uri: "/get-document-by-filter"
    accept: ${event-query-web-client.webclient.accept-type}
  query-definitions:
    method: GET
    uri: "/get-process-definitions"
    accept: ${event-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false

user-config:
  username: test
  password: test
  roles: USER